/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 racket1.glb -T 
Files: racket1.glb [44.93MB] > D:\AAAA_WEB_DEV 22 03 2025\000_TGP PROJEKY\029_hohewarte\05animatedjs\public\models\racket1-transformed.glb [675.64KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Racket1(props) {
  const { nodes, materials } = useGLTF('/models/racket1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Racket.geometry} material={materials.racket} />
    </group>
  )
}

useGLTF.preload('/models/racket1-transformed.glb')
