/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tennis_ball1.glb -T 
Files: tennis_ball1.glb [79.18MB] > D:\AAAA_WEB_DEV 22 03 2025\000_TGP PROJEKY\029_hohewarte\05animatedjs\public\models\tennis_ball1-transformed.glb [5.77MB] (93%)
Author: Arman.Abgaryan (https://sketchfab.com/Arman.Abgaryan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tennis-ball-8f1cbc19dc414ad89097eabe063ada88
Title: Tennis Ball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tennis_ball1(props) {
  const { nodes, materials } = useGLTF('/models/tennis_ball1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.standardSurface6SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/tennis_ball1-transformed.glb')
